# Generated by Django 3.2.8 on 2021-10-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanggalTersedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('sentra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daftar_vaksinasi.sentravaksinasi')),
            ],
        ),
        migrations.CreateModel(
            name='JamTersedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.TextField(max_length=10)),
                ('tanggal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daftar_vaksinasi.tanggaltersedia')),
            ],
        ),
    ]
