# Generated by Django 3.2.8 on 2021-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0003_alter_jamtersedia_jam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamtersedia',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='jamtersedia',
            name='tanggal',
            field=models.ManyToManyField(to='daftar_vaksinasi.TanggalTersedia'),
        ),
        migrations.RemoveField(
            model_name='tanggaltersedia',
            name='sentra',
        ),
        migrations.AddField(
            model_name='tanggaltersedia',
            name='sentra',
            field=models.ManyToManyField(to='daftar_vaksinasi.SentraVaksinasi'),
        ),
    ]
