# Generated by Django 3.2.8 on 2021-10-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0004_auto_20211027_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamtersedia',
            name='tanggal',
        ),
        migrations.RemoveField(
            model_name='tanggaltersedia',
            name='sentra',
        ),
        migrations.AddField(
            model_name='sentravaksinasi',
            name='list_of_tanggal',
            field=models.ManyToManyField(to='daftar_vaksinasi.TanggalTersedia'),
        ),
        migrations.AddField(
            model_name='tanggaltersedia',
            name='list_of_jam_tersedia',
            field=models.ManyToManyField(to='daftar_vaksinasi.JamTersedia'),
        ),
        migrations.AlterField(
            model_name='jamtersedia',
            name='jam',
            field=models.CharField(max_length=20),
        ),
    ]
