# Generated by Django 3.2.8 on 2021-11-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0005_auto_20211028_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentravaksinasi',
            name='list_of_tanggal',
        ),
        migrations.RemoveField(
            model_name='tanggaltersedia',
            name='list_of_jam_tersedia',
        ),
        migrations.AlterField(
            model_name='sentravaksinasi',
            name='kabupaten_kota',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sentravaksinasi',
            name='provinsi',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PesertaVaksinasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('nik', models.CharField(max_length=50)),
                ('jam_vaksinasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daftar_vaksinasi.jamtersedia')),
                ('sentra_vaksinasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daftar_vaksinasi.sentravaksinasi')),
                ('tanggal_vaksinasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daftar_vaksinasi.tanggaltersedia')),
            ],
        ),
    ]
