# Generated by Django 3.2.8 on 2021-11-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0007_auto_20211103_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesertavaksinasi',
            name='sentra_vaksinasi',
            field=models.TextField(null=True),
        ),
    ]
