# Generated by Django 3.2.8 on 2021-11-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0008_alter_pesertavaksinasi_sentra_vaksinasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesertavaksinasi',
            name='kabupaten_kota',
        ),
        migrations.RemoveField(
            model_name='pesertavaksinasi',
            name='provinsi',
        ),
        migrations.AlterField(
            model_name='pesertavaksinasi',
            name='jam_vaksinasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daftar_vaksinasi.jamtersedia'),
        ),
        migrations.AlterField(
            model_name='pesertavaksinasi',
            name='sentra_vaksinasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daftar_vaksinasi.sentravaksinasi'),
        ),
        migrations.AlterField(
            model_name='pesertavaksinasi',
            name='tanggal_vaksinasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daftar_vaksinasi.tanggaltersedia'),
        ),
        migrations.AlterField(
            model_name='sentravaksinasi',
            name='kabupaten_kota',
            field=models.CharField(default='Kab/Kota', max_length=100),
        ),
        migrations.AlterField(
            model_name='sentravaksinasi',
            name='provinsi',
            field=models.CharField(default='provinsi', max_length=100),
        ),
        migrations.DeleteModel(
            name='KabupatenKota',
        ),
        migrations.DeleteModel(
            name='Provinsi',
        ),
    ]
