# Generated by Django 3.2.8 on 2021-11-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0010_auto_20211103_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesertavaksinasi',
            name='vaksinasi_ke',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=1, null=True),
        ),
    ]
