# Generated by Django 3.2.8 on 2021-11-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0011_pesertavaksinasi_vaksinasi_ke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesertavaksinasi',
            old_name='alamat',
            new_name='alamat_sentra_vaksinasi',
        ),
        migrations.RenameField(
            model_name='sentravaksinasi',
            old_name='alamat',
            new_name='alamat_sentra_vaksinasi',
        ),
    ]
