# Generated by Django 3.2.8 on 2021-11-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daftar_vaksinasi', '0012_auto_20211104_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesertavaksinasi',
            name='kabupaten_kota',
        ),
        migrations.RemoveField(
            model_name='pesertavaksinasi',
            name='provinsi',
        ),
    ]
